package com.hibernate.client;

import org.hibernate.Session;

import com.hibernate.entity.Employee;
import com.hibernate.utility.HibernateUtility;

public class EmployeeClient_1_FirstLevelCache {

	public static void main(String[] args) {
		Employee employee = null;
		
		Session session = HibernateUtility.getSessionFactory().openSession();
		session.beginTransaction();
		
		System.out.println("is Employee ID 1003 is in first level cache[Persistence context] - before? "+session.contains(employee));
		employee = session.get(Employee.class, 1003);
		System.out.println("is Employee ID 1003 is in first level cache - after? "+session.contains(employee));
		System.out.println(employee.getEmployeeId()+", "+employee.getEmployeeName());
		
		
		System.out.println("is Employee ID 1003 is in first level cache - after - load in current session? "+session.contains(employee));
		employee = session.get(Employee.class, 1003);
		System.out.println("is Employee ID 1003 is in first level cache - after called - load in current session? "+session.contains(employee));
		System.out.println(employee.getEmployeeId()+", "+employee.getEmployeeName());
		
		session.getTransaction().commit();
		session.close();
		
		HibernateUtility.shutdownSessionFactory();
	}

}
//Observation:  SQL queries generated by framework only one, but two hits