package com.hibernate.client;

import org.hibernate.Session;

import com.hibernate.entity.Employee;
import com.hibernate.utility.HibernateUtility;

public class EmployeeClient_3_FirstLevelCache_tworeferences {

	public static void main(String[] args) {
		
		Session session = HibernateUtility.getSessionFactory().openSession();
		session.beginTransaction();
		
		Employee employee1 = session.get(Employee.class, 1003);
		System.out.println("is Employee ID 1003 is in first level cache - after? "+session.contains(employee1));
		System.out.println(employee1.getEmployeeId()+", "+employee1.getEmployeeName());
		
		
		Employee employee2 = session.get(Employee.class, 1003);
		System.out.println("is Employee ID 1003 is in first level cache - after called - load in current session? "+session.contains(employee2));
		System.out.println(employee2.getEmployeeId()+", "+employee2.getEmployeeName());
		
		session.getTransaction().commit();
		session.close();
		
		HibernateUtility.shutdownSessionFactory();
	}

}
//Observation:  SQL queries generated by framework only one, but two hits
// employee object is available in session so query fired only once in the logs